version: '3.8'
services:
  laravel-app:
    build: .
    container_name: laravel-app
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: momdoctor
    ports:
      - "3306:3306"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge